// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpajzManager.Api.DbContexts;

#nullable disable

namespace SpajzManager.Api.Migrations
{
    [DbContext(typeof(SpajzManagerContext))]
    [Migration("20250330145024_StorageTypeInsteadOfStrings")]
    partial class StorageTypeInsteadOfStrings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SpajzManager.Api.Entities.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Households");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Szülői ház",
                            Name = "Városlődi kecó"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Albérlet",
                            Name = "Palotai kégli"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nyaraló",
                            Name = "Györöki kisház"
                        });
                });

            modelBuilder.Entity("SpajzManager.Api.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("StorageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("StorageId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SpajzManager.Api.Entities.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("StorageTypeId");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("SpajzManager.Api.Entities.StorageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StorageTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ideiglenes tároló"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hűtő"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fagyasztó"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tároló "
                        },
                        new
                        {
                            Id = 5,
                            Name = "Spájz"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pince"
                        });
                });

            modelBuilder.Entity("SpajzManager.Api.Entities.Item", b =>
                {
                    b.HasOne("SpajzManager.Api.Entities.Household", "Household")
                        .WithMany("Items")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpajzManager.Api.Entities.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId");

                    b.Navigation("Household");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("SpajzManager.Api.Entities.Storage", b =>
                {
                    b.HasOne("SpajzManager.Api.Entities.Household", "Household")
                        .WithMany("Storages")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpajzManager.Api.Entities.StorageType", "Type")
                        .WithMany()
                        .HasForeignKey("StorageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SpajzManager.Api.Entities.Household", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Storages");
                });
#pragma warning restore 612, 618
        }
    }
}
